#!/bin/bash
#Ce script a pour but de de placer une ligne de commande permettant de faire les mises des paquets tous les dimanches a 4h dans le crontab si elle n'y ai pas deja.

if crontab -l | grep -q "sudo apt-get update >> var/log/update_script.log && sudo apt-get upgrade -y >> /var/log/update_script.log"
then
	echo "script was already in crontab file."
else
	crontab < <(crontab -l ; echo "0 4 * * sun    sudo apt-get update >> var/log/update_script.log && sudo apt-get upgrade -y >> /var/log/update_script.log")	
	echo "script has been put into crontab file."
fi
